name: publishGitPages

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Publish with dotnet
      run: dotnet publish Imc/Imc.csproj --configuration Release --output build
    # changes the base-tag in index.html from '/' to 'BlazorAppSpendsRegister' to match GitHub Pages repository subdirectory
    # - name: Change base-tag in index.html from / to BlazorAppSpendsRegister
    #   run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorAppSpendsRegister\/" \/>/g' build/wwwroot/index.html
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        # GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/wwwroot